service: ogubot

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1 # Tokyo
  role: arn:aws:iam::482059563409:role/ogubot-role

package:
  exclude:
    # npm i phantom で入るphantomjs-prebuiltは入れずに、代わりに
    # プロジェクトルートにおいたLinux用バイナリを使う
    - node_modules/phantom/node_modules/phantomjs-prebuilt/**
    - node_modules/phantomjs-prebuilt/**
    - phantomjs.exe


functions:
  tweet:
    handler: dist/src/tweet/handler.handler
    timeout: 60
