service: aws-nodejs

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1 # Tokyo

package:
  exclude:
    - node_modules/**

functions:
  ogubot:
    handler: dist/handler.ogubot
    events:
      # 定期実行の設定
      - schedule:
        name: my-schedule
        description: Invoke per an hour
        rate: cron(1 hour)
        enabled: true
