service: line-bot

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1 # Tokyo

functions:
  ogubot:
    handler: dist/src/handler.ogubot
    events:
      # 定期実行の設定
      - schedule:
        name: my-schedule
        description: "Invoke per an hour"
        rate: cron(1 hour)
        enabled: true

environment:
  # consumer_key: ${file(test/config.json):consumer_key}